// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHcK3fA9SrkPwKZ0dbzUwyWcZESGHzPuc',
    appId: '1:347816522023:web:2a9cf2ea5c30b14fef3902',
    messagingSenderId: '347816522023',
    projectId: 'kohatian-foundation',
    authDomain: 'kohatian-foundation.firebaseapp.com',
    storageBucket: 'kohatian-foundation.appspot.com',
    measurementId: 'G-1P0XVXRCMM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB60evtaaCEnRiUeZn3U-eWY5pDMGOBP64',
    appId: '1:347816522023:android:4ef7404cea74a16bef3902',
    messagingSenderId: '347816522023',
    projectId: 'kohatian-foundation',
    storageBucket: 'kohatian-foundation.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUqptGzDLyjtzblnEMMpGZm3sjHCZwLyQ',
    appId: '1:347816522023:ios:33a2848ff1f52178ef3902',
    messagingSenderId: '347816522023',
    projectId: 'kohatian-foundation',
    storageBucket: 'kohatian-foundation.appspot.com',
    androidClientId: '347816522023-3um0qb82sf01nthsgn8tik97kuct767g.apps.googleusercontent.com',
    iosClientId: '347816522023-r38lvl7baqr429ghf6dfvtr8vdanh0mg.apps.googleusercontent.com',
    iosBundleId: 'com.enigmatek.pk.kohatianFoundation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUqptGzDLyjtzblnEMMpGZm3sjHCZwLyQ',
    appId: '1:347816522023:ios:33a2848ff1f52178ef3902',
    messagingSenderId: '347816522023',
    projectId: 'kohatian-foundation',
    storageBucket: 'kohatian-foundation.appspot.com',
    androidClientId: '347816522023-3um0qb82sf01nthsgn8tik97kuct767g.apps.googleusercontent.com',
    iosClientId: '347816522023-r38lvl7baqr429ghf6dfvtr8vdanh0mg.apps.googleusercontent.com',
    iosBundleId: 'com.enigmatek.pk.kohatianFoundation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHcK3fA9SrkPwKZ0dbzUwyWcZESGHzPuc',
    appId: '1:347816522023:web:c24cfe5ced7b005cef3902',
    messagingSenderId: '347816522023',
    projectId: 'kohatian-foundation',
    authDomain: 'kohatian-foundation.firebaseapp.com',
    storageBucket: 'kohatian-foundation.appspot.com',
    measurementId: 'G-RPPVV5GYQL',
  );

}